package com.tqi.analisecredito.api.exception;

public class RecursoNaoEncontradoException extends RuntimeException {

    public RecursoNaoEncontradoException(String message) {
        super(message);
    }

    public RecursoNaoEncontradoException(String nomeRecurso, String idRecurso) {
        this(String.format("Recurso n√£o encontrado para %s {%s}", nomeRecurso, idRecurso));
    }
}
